language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install codecov
install:
  - make dev
script:
  - make test-format test
after_success:
  - codecov
